dataset_name: "Petroleum_NZ"
csv_name: "preprocessed_nz.csv"
data_dir: "./data/"
results_dir: "experiment_petroleum"
log_dir: "logs"
runs_dir: "runs"

features: ["GR", "DENS", "DTC", "DRHO", "RESS", "RESD", "RESM"]
target_col: "CLASS"
seq_len: 100
add_time: "no"

num_epochs: 40
batch_size: 256
lr: 0.001
weight_decay: 0.0001
hidden_dim: 128
tolerances: [0.001]

experiments_to_run:
  qformer: true
qformer_params:
  kernels: ['gaussian']
  aggregations: ["concat"]
  # Разные уровни "зрения": 0.05 (поиск резких скачков), 0.2, 0.5, 1.0 (глобальный тренд)
  bandwidth_lists_different:
    - [0.05, 0.2, 0.5, 1.0]